project_id = "wossuijahchhtjzphsgh"

[functions.create-investment-poll]
verify_jwt = true

[functions.cast-poll-vote]
verify_jwt = true

[functions.get-hedera-balance]
verify_jwt = true

[functions.associate-hedera-token]
verify_jwt = true

[functions.buy-marketplace-tokens]
verify_jwt = true

[functions.check-token-association]
verify_jwt = true

[functions.transfer-hedera-tokens]
verify_jwt = true

[functions.create-marketplace-listing]
verify_jwt = true

[functions.distribute-hedera-revenue]
verify_jwt = true

[functions.register-property-blockchain]
verify_jwt = false

[functions.record-hcs-event]
verify_jwt = false

[functions.trade-tokens]
verify_jwt = true

[functions.create-hedera-token]
verify_jwt = false

[functions.create-hcs-topic-and-token]
verify_jwt = false